import hashlib
import io
import logging


LOG = logging.getLogger(__name__)


def load_hashtable(path):
    """
    Reads a list of hash digests as generated by the linux tool `sha256sum`.
    Returns a `dict` object with filenames as keys and digests as values.
    """
    result = {}
    with open(path, 'r') as f:
        for line in f:
            hashval, filename = line.split('  ', 1)
            result[filename.rstrip()] = hashval

    return result


def assert_match(found, expected, path, algorithm, on_mismatch):
    if found != expected:
        msg = f'{path}: {algorithm} checksum mismatch; found: {found}; expected: {expected}'
        if on_mismatch == 'raise':
            raise ValueError(msg)
        elif on_mismatch == 'warn':
            LOG.warning(msg)
        elif on_mismatch == 'ignore':
            pass
        else:
            raise ValueError(f'illegal action: {on_mismatch}')


def check_file(path, expected_digest, algorithm='sha256', on_mismatch='raise'):
    m = hashlib.new(algorithm)
    with open(path, 'rb') as f:
        m.update(f.read())

    assert_match(m.hexdigest(), expected_digest, path, algorithm, on_mismatch)


class sha256_open:
    """
    Replacement for the `open` function which transparently checks the message
    digest. If there is a mismatch, an exception is raised.

    Currently, limitations are as follows:
    - only SHA256 digests are supported; and
    - the file must be read fully and sequentially.
    """
    def __init__(self, path, hashvalue, mode='t', encoding='utf8', on_mismatch='raise'):
        self.path = path
        self.hashvalue = hashvalue
        self._mode = mode
        self._encoding = encoding
        self._on_mismatch = on_mismatch

        for illegal_mode in 'wxa+':
            assert illegal_mode not in self._mode, f'mode {illegal_mode} not supported'

    def __enter__(self):
        self._f = open(self.path, 'br')
        self._m = hashlib.sha256()

        if 't' in self._mode:
            return io.TextIOWrapper(io.BufferedReader(self), encoding=self._encoding)
        else:
            return self

    def read(self, size=-1):
        b = self._f.read(size)
        self._m.update(b)
        return b

    def readall(self):
        b = self._f.read()
        self._m.update(b)
        return b

    def readinto(self, b):
        n = self._f.readinto(b)
        if n is not None:
            self._m.update(b[:n])
        return n

    def check_digest(self):
        assert_match(self._m.hexdigest(), self.hashvalue, self.path, algorithm='sha256', on_mismatch=self._on_mismatch)

    def close(self):
        self.check_digest()
        self._f.close()

    def __getattr__(self, name):
        return eval(f'self._f.{name}')

    def __exit__(self, exc_type, exc_value, traceback):
        try:
            if exc_type is None:
                self.check_digest()
        finally:
            self._f.close()
